from __future__ import annotations
from typing import List, Any, Dict, Tuple, Union
import numpy as np

__all__: list[str]
__doc__: str
__version__: str

def listobs(fitsfilepath: str, sids: List[int] = List) -> Any: ...
def split(fitsfilepath: str, outfitsfilepath: str, sids: List[int] = [], baseline_ids: List[int] = List, freqids : List[int] = List,
          source_col : str = "SOURCE", baseline_col : str = "BASELINE", frequency_col : str = "FREQID",
          expression : str = "", reindex : bool = False, verbose : bool = True,
          ) -> Any: ...


class HeaderCard:
    key: str
    value: Any

class HeaderManager:
    all_hdus: Dict[int, List[HeaderCard]]

class ReadIO:
    header_mgr: HeaderManager
    def __init__(self) -> None: ...
    def open(self, fitsfilepath: str, writeable: bool = ...) -> bool: ...
    def close(self) -> None: ...
    def flush(self) -> None: ...
    
    def save_as(outfitsfilepath:str,uv_data_dict_by_hdu:Dict, verbose:bool) ->None: ...
    
    def fetch_header(self) -> Dict[int, List[HeaderCard]]: ...
    
    def update_header_int(self, hdu_num: int, key: str, val: int, com: str) -> None: ...
    def update_header_double(self, hdu_num: int, key: str, val: float, com: str) -> None: ...
    def update_header_str(self, hdu_num: int, key: str, val: str, com: str) -> None: ...
    def write_table_column(self, hdu_num: int, colname: str, data: Union[List[str], List[bytes], np.ndarray], start_row: int = 0) -> None: ...
    
    def read_hdutable(self, hdu_num:int) -> None: ...
    def read_table_chunked(self) -> None: ...
    
    def listobs(self, sids:list[str]=None) -> None: ...
    def get_fits_byte_size(self) -> Tuple[int, int]: ...
    
    def delete_header_key(self, hdu_num: int, key: str) -> None: ...
    def delete_hdu(self, hdu_num: int) -> None: ...
    
    
    